apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bhsjj0yvq-go 
  janus-idp.io/tekton: bhsjj0yvq-go
  backstage.io/kubernetes-id: bhsjj0yvq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bhsjj0yvq-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  