apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bhsjj0yvq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bhsjj0yvq-go 
  name: bhsjj0yvq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bhsjj0yvq-go 
